manifest:
  version: "0.12"
  remotes:
    - name: zephyr_ms88sf2
      url-base: git@github.com:kamejoko80/zephyr_ms88sf2.git
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  defaults:
    remote: zephyr_ms88sf2

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: 41814f8c3bb076656197a78700d2b41ea9500c38
      import:
        name-whitelist:
          - cmsis
          - edtt
          - fatfs
          - hal_nordic
          - libmetal
          - littlefs
          - lvgl
          - mbedtls
          - mcumgr
          - mipi-sys-t
          - net-tools
          - nrf_hw_models
          - openthread
          - segger
  self:
    path: ms88sf2